# Decent Vectorized Prediction Algo 

No more white milk.

In [3]:
from functools import partial
import numpy as np


In [72]:
def criterion(m_matrix, m_filter=slice(None,None), a_filter=slice(None,None), aggregation=partial(np.sum, axis=1)):
    """
    Typical usecase 
    
    m_matrix = m_fimps
    
    m_filter = available models
    a_filter = available attributes.
    
    """
    
    
    c_matrix = np.ones(m_matrix.shape[0])*-1
    c_matrix[m_filter] = aggregation(m_matrix[m_filter,a_filter])
    return c_matrix

In [56]:
slice(1,-1)

slice(1, -1, None)

In [70]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [65]:
a.shape

(10,)

In [71]:
a[slice(None,None)]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
def mrai(m_fimps):
    return m_sel

In [89]:
m_codes = np.array(
[
    [0,0,0,1],
    [0,0,1,-1],
    [-1,0,0,1]
]
)

In [111]:
m_codes = np.random.randint(-1,2, size=(100,100))

array([[ 0,  0, -1, ...,  1, -1, -1],
       [-1,  1, -1, ..., -1, -1, -1],
       [-1,  0,  0, ...,  1,  0,  1],
       ...,
       [-1, -1,  0, ...,  1, -1, -1],
       [ 1, -1,  0, ...,  0,  0,  1],
       [ 0, -1, -1, ...,  0, -1,  1]])

In [119]:
size = 10**4
m_codes = np.random.randint(-1,2, size=(10*size,size))

m_fimps = np.zeros(m_codes.shape)
m_fimps[np.where(m_codes == 0)] = np.random.rand(len(m_fimps[np.where(m_codes == 0)]))

m_score = np.zeros(m_codes.shape)
#m_score[np.where(m_codes == 1)] = np.random.rand(len(m_score[np.where(m_codes == 1)]))
m_score[np.where(m_codes == 1)] = 1

#m_fimps, m_score



In [120]:
%%timeit
src_crit = criterion(m_fimps, a_filter=[0,1])
tgt_crit = criterion(m_score, a_filter=[3])
src_crit * tgt_crit

8.5 ms ± 667 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [87]:
src_crit * tgt_crit

array([1.31102792, 0.        , 0.00394713])

In [ ]:
m_fimps = 

In [ ]:
c_matrix

In [37]:
np.random.randint(3)

1