In [84]:
from functools import partial
import numpy as np

In [ ]:
def criterion(m_matrix, m_filter=None, a_filter=None, aggregation=partial(np.sum, axis=1)):
    c_matrix = np.ones(m_matrix.shape[0])*-1
    c_matrix[m_filter] = aggregation(m_matrix[m_filter,a_filter])
    return c_matrix

In [100]:
a = np.zeros((10,8))
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [105]:
b = a[0:2, :]
c = a[[2,3], :] 
d = a[[4,5], ] 
b, c, d

(array([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]))

In [106]:
def parallel_composition(m_list):
    return

In [107]:
b,c,d

(array([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]]),
 array([[8., 8., 8., 8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8., 8., 8., 8.]]),
 array([[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]))

In [108]:
a

array([[2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [313]:
import numpy as np
import sklearn
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

In [349]:
X = np.random.randint(4, size=(100, 4))

dt1 = DecisionTreeClassifier()
dt1.fit(X[:,:-1], X[:,-1])

dt1.desc_ids = [1,2,3]
dt1.targ_ids = [4]

X[:, -1] = X[:, -1]+1

dt2 = DecisionTreeClassifier()
dt2.fit(X[:,:-1], X[:,-1])

dt2.desc_ids = [1,2,5]
dt2.targ_ids = [4]

dt3 = DecisionTreeClassifier()
dt3.fit(X[:,:-1], X[:,-2:])

dt3.desc_ids = [1,2, 3]
dt3.targ_ids = [3, 4]

In [340]:
def _uniform_predict(f):
    def predict(*args, **kwargs):
        return f(*args, **kwargs).reshape(-1,1)
    return predict

def _uniform_predict_proba(f):
    def predict_proba(*args, **kwargs):
        return [f(*args, **kwargs)]
    return predict_proba

In [350]:
class standard_model:

    attributes = {
        "desc_ids",
        "targ_ids",
        "predict",
        "n_outputs_",
        "predict_proba",
        "classes_",
        "predict",
    }

    def __init__(self, m):
        self.model = m

        for a in self.attributes:
            v = getattr(m, a, None)
            if v is not None:
                setattr(self, a, v)

        return

In [351]:
dt1.yorrick = 'AHA'
s = standard_model(dt1)

del dt1

In [352]:
s.predict(X[:, :-1])

array([2, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 2, 0, 2, 2, 1, 2, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 1, 0,
       0, 2, 1, 1, 1, 0, 2, 2, 1, 0, 0, 0, 0, 3, 0, 2, 1, 0, 0, 0, 3, 1,
       0, 2, 3, 1, 0, 1, 1, 2, 3, 0, 0, 2, 1, 0, 2, 1, 0, 1, 1, 0, 1, 1,
       1, 2, 0, 2, 1, 1, 0, 2, 3, 0, 1, 2])

AttributeError: 'standard_model' object has no attribute 'YORRICK'

In [314]:
def uniform_model(m):
    
    if m.n_outputs_ == 1:
        if isinstance(m, sklearn.tree.DecisionTreeClassifier):
            m.predict = _uniform_predict(m.predict)
            m.predict_proba = _uniform_predict_proba(m.predict_proba)
            m.classes_ = [m.classes_]
            m.n_classes_ = [m.n_classes_]
    
        if isinstance(m, sklearn.tree.DecisionTreeRegressor):
            m.predict = _uniform_predict(m.predict)

    return m

In [319]:
m_list = [uniform_model(m) for m in (dt1, dt2, dt3)]

In [323]:
getattr(m, 'predict_proba')

<bound method DecisionTreeClassifier.predict_proba of DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')>

In [325]:
setattr(m, 'YEAH', 3)

In [326]:
m.YEAH

3

In [317]:
m_list[0].predict_proba(X[:, :-1])

TypeError: slice indices must be integers or None or have an __index__ method

In [299]:
for m in m_list:
    pass

In [310]:
hasattr(m, 'classes_')

True

In [305]:
dt1.n_outputs_

1

In [302]:
dt2.n_classes_

4

In [293]:
f = _uniform_predict(dt1.predict)

A


In [297]:
dt2.predict_proba = _uniform_predict(dt1.predict_proba)
dt1.predict = _uniform_predict_proba(dt1.predict)

NameError: name 'args' is not defined

In [292]:
dt1.predict(X[:, :-1])

A


array([[3],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [3],
       [0],
       [0],
       [0],
       [2],
       [3],
       [0],
       [1],
       [1],
       [1],
       [0],
       [2],
       [1],
       [1],
       [0],
       [0],
       [2],
       [0],
       [3],
       [0],
       [2],
       [2],
       [0],
       [2],
       [3],
       [2],
       [0],
       [0],
       [1],
       [2],
       [2],
       [1],
       [3],
       [0],
       [3],
       [1],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [2],
       [1],
       [1],
       [1],
       [2],
       [3],
       [0],
       [0],
       [0],
       [2],
       [0],
       [3],
       [2],
       [3],
       [1],
       [0],
       [3],
       [0],
       [0],
       [1],
       [2],
       [0],
       [0],
       [1],
       [1],
       [0],
       [2],
       [0],
       [1],
       [0],
       [0],
       [1],
       [2],
       [3],
    

In [277]:
dt1.predict

<function __main__._uniform_predict.<locals>.predict(*args, **kwargs)>

A


array([[3],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [3],
       [0],
       [0],
       [0],
       [2],
       [3],
       [0],
       [1],
       [1],
       [1],
       [0],
       [2],
       [1],
       [1],
       [0],
       [0],
       [2],
       [0],
       [3],
       [0],
       [2],
       [2],
       [0],
       [2],
       [3],
       [2],
       [0],
       [0],
       [1],
       [2],
       [2],
       [1],
       [3],
       [0],
       [3],
       [1],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [2],
       [1],
       [1],
       [1],
       [2],
       [3],
       [0],
       [0],
       [0],
       [2],
       [0],
       [3],
       [2],
       [3],
       [1],
       [0],
       [3],
       [0],
       [0],
       [1],
       [2],
       [0],
       [0],
       [1],
       [1],
       [0],
       [2],
       [0],
       [1],
       [0],
       [0],
       [1],
       [2],
       [3],
    

In [173]:
dt1.desc_ids

[1, 2, 5]

In [246]:
class ParallelComposition():
    
    def __init__(self, m_list):
        self.desc_ids = []
        self.targ_ids = []
        self.m_list = m_list
        for m in m_list:
            self.desc_ids += m.desc_ids
            self.targ_ids += m.targ_ids
        return
    
    def predict(self, X):
        return
    
    def predict_proba(self, X):
        return
    
    def predict_numer(self, X):
        return

In [247]:
m_list = [dt1, dt2, dt3]
pc = ParallelComposition(m_list)

In [248]:
pc.desc_ids, pc.targ_ids

([1, 2, 3, 1, 2, 5, 1, 2, 3], [4, 4, 3, 4])

In [249]:
res_numer = np.zeros((X.shape[0], len(pc.targ_ids)))
res_numer.shape

(100, 4)

In [263]:
y_preds = [np.atleast_2d(m.predict(X[:,:-1])).T for m in m_list]


In [260]:
y_preds[-1].shape

(100, 2)

In [261]:
y_preds[0].shape

(1, 100)

In [264]:
np.vstack(y_preds).reshape(X.shape[0], -1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 2 has size 100

[1, 2, 3, 1, 2, 5]

[4, 4]

(100, 2)

In [164]:
[]+[3,5]

[3, 5]

In [154]:
res_numer = np.empty((1000))

In [157]:
pc.predict[0](X[:, :-1])

array([0, 1, 2, 0, 1, 0, 1, 2, 1, 0, 3, 0, 0, 0, 0, 2, 3, 3, 2, 0, 1, 3,
       1, 3, 2, 0, 0, 0, 0, 1, 1, 3, 1, 0, 3, 0, 0, 3, 1, 3, 0, 1, 1, 0,
       0, 2, 0, 0, 3, 2, 1, 2, 3, 0, 3, 1, 0, 3, 2, 0, 1, 2, 3, 1, 1, 3,
       2, 3, 0, 0, 1, 2, 0, 0, 0, 0, 1, 3, 3, 3, 0, 0, 1, 0, 3, 2, 3, 2,
       2, 0, 1, 1, 2, 0, 0, 3, 3, 0, 0, 0])

In [144]:
del dt1

In [146]:
pc.m_list[0]

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [131]:
dt1.classes_, dt2.classes_

(array([0, 1, 2, 3]), array([1, 2, 3, 4]))

In [139]:
all_classes = np.unique(np.vstack([dt1.classes_, dt2.classes_]))

_pad_proba(dt1.classes_, all_classes)(dt1.predict_proba(X[:,:-1]))

array([[0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.66666667, 0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.66666667, 0.33333333, 0.        , 0.        ],
       [0.5       , 0.25      , 0.        , 0.25      , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.5       , 0.        , 0.        , 0.5       , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.        , 0.5       , 0.        , 0.5       , 0.        ],
       [0.        , 0.25      , 0.75      , 0.        , 0.        ],
       [0.5       , 0.5       , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.25      , 0.        , 0.75      , 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.25      , 0.25      , 0.5       , 0.        ],
       [0.5       , 0.        , 0.

In [265]:
# Helpers
def _pad_proba(classes, all_classes):
    idx = _map_classes(classes, all_classes)

    def pad(X):
        R = np.zeros((X.shape[0], len(all_classes)))
        R[:, idx] = X
        return R

    return pad


def _map_classes(classes, all_classes):
    sorted_idx = np.argsort(all_classes)
    matches = np.searchsorted(all_classes[sorted_idx], classes)
    return sorted_idx[matches]


def _select_numeric(idx):
    def select(X):
        if len(X.shape) > 1:
            return X[:, idx]
        elif len(X.shape) == 1:
            return X

    return select


def _select_nominal(idx):
    def select(X):
        if isinstance(X, list):
            return X[idx]
        elif isinstance(X, np.ndarray):
            return X

    return select

In [ ]:
def _uniform(f):
    def predict(*args, **kwargs):
        
        return
    return

NameError: name 'all_classes' is not defined

In [122]:
dt1.predict(X[:,:-1])

NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

NameError: name 'X' is not defined

In [2]:
G = nx.DiGraph()

In [5]:
G.add_nodes_from({'a', 'b', 'c'})

In [21]:
G.add_edges_from([('a', 'c', dict(color='red')), ('b', 'c')])

In [22]:
G.nodes

NodeView(('b', 'c', 'a'))

In [27]:
G.edges(data=True)

OutEdgeDataView([('b', 'c', {}), ('a', 'c', {'color': 'red'})])

In [28]:
g = G.subgraph(['a', 'c'])

In [29]:
g.nodes, g.edges

(NodeView(('c', 'a')), OutEdgeView([('a', 'c')]))

In [32]:
g.edges(data=True)

OutEdgeDataView([('a', 'c', {'color': 'red'})])

In [39]:
np.zeros(10).reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [40]:
partial(np.sum, axis=1)

functools.partial(<function sum at 0x7fb4d41ac0e0>, axis=1)

In [42]:
np.sum(np.ones((2,10)), axis=1)

array([10., 10.])

In [47]:
import pympler
from pympler.asizeof import asizeof

In [49]:
asizeof(3)

32

In [57]:
asizeof()/10**6

800.000112

In [67]:
a = np.zeros((1500,3000))
a[1,1] = 1
a[2,1] = 1

In [69]:
np.sparse(a)

AttributeError: module 'numpy' has no attribute 'sparse'

In [81]:
from scipy import sparse
b=sparse.csr_matrix(a)

In [82]:
b

<1500x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [80]:
b*np.zeros(3000)

array([0., 0., 0., ..., 0., 0., 0.])

In [76]:
np.save('arraysparse', b)

In [77]:
np.save('array', a)