In [1]:
import numpy as np

In [3]:
q_code = np.zeros(10)
q_code[[6,7]] = 1
q_code[[3,4]] = -1
q_code

array([ 0.,  0.,  0., -1., -1.,  0.,  1.,  1.,  0.,  0.])

In [14]:
avl_targ = (q_code == 1).astype(int)
avl_targ

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [7]:
avl_targ

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [16]:
np.eye(avl_targ.shape[0], dtype=int)[np.where(avl_targ)[0]].T

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 0]])

In [18]:
criteria = np.array([0.5,0.3,0.2])
criteria

array([0.5, 0.3, 0.2])

In [28]:
avl_mods = np.array([[0,0,1],
                     [0,1,0]])

In [29]:
criteria * avl_mods

array([[0. , 0. , 0.2],
       [0. , 0.3, 0. ]])